- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- website/docs/r/device.html.markdown
> packet_device: Add PXE arguments

- CHANGELOG.md
- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- website/docs/r/device.html.markdown
This PR make it possible to read the temporary root password on new device.
> Add field for root password

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
> Fix iPXE Related Validations

- packet/resource_packet_volume.go
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/ip.go
- vendor/github.com/packethost/packngo/packngo.go
- vendor/github.com/packethost/packngo/volumes.go
- vendor/vendor.json
Bumping packngo to newest version adding
- volume attachments
- floating ip subnet handling
- HTTP unauthorized error message
- spot instance test
> Packngo bump

- CHANGELOG.md
- packet/provider.go
- packet/resource_packet_volume.go
- packet/resource_packet_volume_attachment.go
- packet/resource_packet_volume_attachment_test.go
- website/docs/r/volume_attachment.html.markdown
- website/packet.erb
This PR adds resource for volume attachment in the Packet provider.
> Add packet_volume_attachment resource

- packet/resource_packet_ssh_key.go
- packet/resource_packet_ssh_key_test.go
Fixed crash for SSH Key resource update, added test to verify the fix.
> Fix SSH key update for #47

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- website/docs/r/device.html.markdown
This adds a "description" attribute to the device, and fixes the update logic for the resource. Plus a test.
fixes #46, #41
> fix device resource update, add description attribute

- packet/resource_packet_project.go
- packet/resource_packet_project_test.go
- website/docs/r/project.html.markdown
This PR fixes update logic for project resource, and adds payment_method_id attribute (and proper handling for it) to the project resource.
fixes #44
> Fix project update

- packet/resource_packet_volume.go
- packet/resource_packet_volume_test.go
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/volumes.go
- vendor/vendor.json
- website/docs/r/volume.html.markdown
This PR bumps packngo and fixes update of the volume resource.
Fixes #60.
> Fix updates of volume resource

- vendor/github.com/packethost/packngo/packngo.go
- vendor/github.com/packethost/packngo/projects.go
- vendor/vendor.json
this adds organization attribute for project creating request
> bump packngo to allow creating projects in nondefault org

- packet/resource_packet_ip_attachment.go
This commit adds a single check for 404 Not Found status code to ensure that
refreshing state of and/or deleting an IP assignment would not result in an
error should the resource could not be found (e.g., it has been already
deleted by other means, etc.).
Signed-off-by: Krzysztof Wilczynski <kw@linux.com>
> Fix. Handle the case when an IP attachment is missing or has been deleted.

- website/docs/r/device.html.markdown
Finding the slugs wasn't delightful, this might help someone in the future.
Signed-off-by: JJ Asghar <jj@chef.io>
> Added more description on how to get slugs

- packet/datasource_spot_market_price.go
- packet/datasource_spot_market_prices.go
- packet/provider.go
- website/docs/d/spot_market_price.html.markdown
- website/packet.erb
@t0mk can you please take a look
This is one bit required for spot market requests to be fully implemented.
> Data source spot market price

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- packet/resource_packet_project.go
- packet/resource_packet_project_test.go
- packet/resource_packet_volume.go
- packet/resource_packet_volume_test.go
- vendor/github.com/packethost/packngo/volumes.go
- vendor/vendor.json
This is addressing issue #51 
Added import to:
- packet_device
- packet_project 
- packet_volume
Tested packet_volume, the SDK was missing include for projects. I've added this PR https://github.com/packethost/packngo/pull/107 once that is merged I will added required acceptance tests.
> Added importer to device and project

- vendor/github.com/packethost/packngo/README.md
- vendor/github.com/packethost/packngo/facilities.go
- vendor/github.com/packethost/packngo/plans.go
- vendor/github.com/packethost/packngo/utils.go
- vendor/vendor.json
This is a packngo bump fixing handling of facilities and plans, to allow for a facility selecting resource.
> bump packngo 2018-12-15

- vendor/github.com/packethost/packngo/virtualnetworks.go
- vendor/vendor.json
Bump of the Go library, containing fix for #78
> packngo bump 2018-12-17

- packet/provider.go
- packet/resource_packet_vlan.go
- packet/resource_packet_vlan_test.go
- website/docs/r/vlan.html.markdown
- website/packet.erb
This PR adds a resource for Virtual Networks. It's the first step toward Packet Layer 2 networking support in the TF provider.
https://help.packet.net/article/57-layer-2-overview
https://help.packet.net/article/58-layer-2-configurations
> New resource: packet_vlan

- CHANGELOG.md
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/ports.go
- vendor/github.com/packethost/packngo/spotmarketrequest.go
- vendor/github.com/packethost/packngo/utils.go
- vendor/vendor.json
This is a hotfix for missing facility code in new provider release
reported in https://github.com/packethost/packngo/pull/129
> bump packngo with dfw2 included

- README.md
instructions on how to set up TF to use the newly developed plugin within a development environment
> [docs] how to use the dev plugin in TF

- website/docs/r/project.html.markdown
the 'payment_method_id' needs to belong to the same 'organization_id'
> clarify the payment_method_id in project.html.markdown

- packet/datasource_packet_precreated_ip_block.go
- packet/resource_packet_ip_attachment.go
- packet/resource_packet_reserved_ip_block.go
- packet/resource_packet_reserved_ip_block_test.go
- website/docs/d/precreated_ip_block.html.markdown
- website/docs/r/reserved_ip_block.html.markdown
this PR extends the IP reservation resource to allow global IPv4
> Global floating IP block reservation

- packet/resource_packet_project.go
- packet/resource_packet_project_test.go
- website/docs/r/project.html.markdown
This PR adds backend_transfer attr to packet_project resource for TF users to take advantage of https://github.com/t0mk/terraform-provider-packet/pull/new/backend_transfer
> Backend transfer

- packet/provider.go
- packet/resource_packet_connect.go
- website/docs/r/connect.html.markdown
- website/packet.erb
this PR adds a resource for Packet Connect - a VLAN "tunnel" to other cloud, at this point Azure
> Add resource for Packet Connect

- go.mod
- go.sum
- vendor/github.com/packethost/packngo/spotmarketrequest.go
- vendor/modules.txt
fixes https://github.com/packethost/packngo/issues/143
> bump to packngo with fixed json serialization tag in spotmarketrequest

- packet/resource_packet_port_vlan_attachment.go
- packet/resource_packet_port_vlan_attachment_test.go
- website/docs/r/port_vlan_attachment.html.markdown
This PR makes it possible to mark attached VLAN as "native" to a port.
> Add support for Native VLAN

- packet/resource_packet_device.go
> extend error message on device creation in nonexistent project

- packet/datasource_packet_device.go
- packet/datasource_packet_device_test.go
- packet/provider.go
- website/docs/d/device.html.markdown
- website/packet.erb
This PR adds a datasource for packet_device
> Add datasource for packet_device

- packet/resource_packet_device.go
Make `failed` one of targets when waiting for device state.
Fail manually after the TF inbuild wait method.
fixes #167
> Better error when created device goes to `failed` state

- packet/resource_packet_device.go
> Add timeouts to packet_device, defaults to 10 min

- website/docs/index.html.markdown
Changed key to facilities from facility and changed string to list.
> Updated Facilities Line to List

- packet/resource_packet_device.go
> Set wait_for_reservation_deprovision to nil if unspecified by user

- packet/datasource_packet_project.go
- packet/datasource_packet_project_test.go
- packet/provider.go
- website/docs/d/project.html.markdown
- website/packet.erb
This PR adds datasource for packet_project
> Add project datasource

- CHANGELOG.md
- packet/resource_packet_spot_market_request.go
Closes #183
@t0mk when you get a chance would you take a look and merge it
> Added missing error handling when waiting for spot instances to complete

- packet/resource_packet_vlan.go
- packet/resource_packet_vlan_test.go
Set vlan facility at import & add test
> Vlan resource import

- website/docs/r/volume_attachment.html.markdown
This PR adds doc snippet showing how to use packet-volume-mounting script via null resource and remote-exec.
> Improve volume attachment doc

- packet/resource_packet_device.go
This fixes a bug in long waits for device state.
> fix wait for device state

- website/docs/d/device.html.markdown
- website/docs/d/operating_system.html.markdown
- website/docs/d/precreated_ip_block.html.markdown
- website/docs/d/spot_market_request.html.markdown
- website/docs/index.html.markdown
- website/docs/r/bgp_session.html.markdown
- website/docs/r/device.html.markdown
- website/docs/r/ip_attachment.html.markdown
- website/docs/r/port_vlan_attachment.html.markdown
- website/docs/r/project_ssh_key.html.markdown
- website/docs/r/reserved_ip_block.html.markdown
- website/docs/r/spot_market_request.html.markdown
- website/docs/r/ssh_key.html.markdown
- website/docs/r/vlan.html.markdown
- website/docs/r/volume.html.markdown
- website/docs/r/volume_attachment.html.markdown
this PR fixes provider docs (at https://www.terraform.io/docs/providers/packet/index.html)
to use 0.12 syntax
> fix expression syntax in examples for 0.12

- go.mod
- go.sum
- vendor/github.com/packethost/packngo/README.md
- vendor/github.com/packethost/packngo/apikeys.go
- vendor/github.com/packethost/packngo/bgp_configs.go
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/ip.go
- vendor/github.com/packethost/packngo/packngo.go
- vendor/github.com/packethost/packngo/ports.go
- vendor/modules.txt
Update packngo dependency in order to use new API features
> packngo update 25022020

- CHANGELOG.md
- packet/resource_packet_device.go
- packet/resource_packet_reserved_ip_block_test.go
- website/docs/r/device.html.markdown
- website/docs/r/reserved_ip_block.html.markdown
This PR implements fields for passing subnets from reserved IP block to new devices.
> Enhanced ip reservations

- CHANGELOG.md
- go.mod
- go.sum
- packet/datasource_packet_device.go
- packet/resource_packet_device.go
- packet/resource_packet_port_vlan_attachment.go
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/ports.go
- vendor/modules.txt
> Bump packngo to version correctly handling hybrid mode for n2.xlarge

- packet/datasource_packet_device.go
- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- website/docs/r/device.html.markdown
…  in favor of `ip_address` attribute and referencing to a reserved IP block
> remove public_ipv4_subnet_size

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
> Make userdata in packet_device ForceNew

- website/docs/d/device.html.markdown
- website/docs/d/device_bgp_neighbors.html.markdown
- website/docs/d/ip_block_ranges.html.markdown
- website/docs/d/operating_system.html.markdown
- website/docs/d/organization.html.markdown
- website/docs/d/precreated_ip_block.html.markdown
- website/docs/d/project.html.markdown
- website/docs/d/spot_market_request.html.markdown
- website/docs/index.html.markdown
- website/docs/r/bgp_session.html.markdown
- website/docs/r/connect.html.markdown
- website/docs/r/device_network_type.markdown
- website/docs/r/ip_attachment.html.markdown
- website/docs/r/organization.html.markdown
- website/docs/r/port_vlan_attachment.html.markdown
- website/docs/r/project.html.markdown
- website/docs/r/project_ssh_key.html.markdown
- website/docs/r/reserved_ip_block.html.markdown
- website/docs/r/ssh_key.html.markdown
- website/docs/r/vlan.html.markdown
- website/docs/r/volume.html.markdown
- website/docs/r/volume_attachment.html.markdown
Hello maintainers 👋
This PR runs `terraform fmt` on all resources and fixes a few typos.
> code formatting and typo fixes

- .github/workflows/release.yml
- .goreleaser.yml
Secrets have been added to repo secrets for the referenced key, passphrase, and token.
> Adds release workflow, and goreleaser config.

- CHANGELOG.md
- go.mod
- go.sum
- packet/datasource_packet_ip_block_ranges.go
- packet/datasource_packet_precreated_ip_block.go
- packet/datasource_packet_project_ssh_key.go
- packet/datasource_packet_project_ssh_key_test.go
- packet/provider.go
- packet/resource_packet_organization.go
- packet/resource_packet_organization_test.go
- packet/resource_packet_project_test.go
- packet/resource_packet_ssh_key.go
- packet/resource_packet_ssh_key_test.go
- website/docs/d/project_ssh_key.html.markdown
- website/packet.erb
Implements #249 
Signed-off-by: Marques Johansson <marques@packet.com>
> add datasource packet_project_ssh_key

- CHANGELOG.md
- GNUmakefile
- packet/errors.go
- packet/resource_packet_bgp_session.go
- packet/resource_packet_device.go
- packet/resource_packet_device_network_type.go
- packet/resource_packet_ip_attachment.go
- packet/resource_packet_port_vlan_attachment.go
- packet/resource_packet_reserved_ip_block.go
- packet/resource_packet_spot_market_request.go
- packet/resource_packet_ssh_key.go
- packet/resource_packet_volume.go
- packet/resource_packet_volume_attachment.go
Addresses https://github.com/packethost/terraform-provider-packet/issues/267
> Improved state removal and state removal logging

- packet/datasource_packet_operating_system_test.go
- packet/resource_packet_spot_market_request_test.go
Signed-off-by: Tomas Karasek <tom.to.the.k@gmail.com>
> fix old slugs in Acceptance Tests

- packet/datasource_packet_precreated_ip_block.go
Signed-off-by: Tomas Karasek <tom.to.the.k@gmail.com>
> Add "type" attr to datasoutce precreated_ip_block

- CHANGELOG.md
Signed-off-by: Tomas Karasek <tom.to.the.k@gmail.com>
> Changelog entry for v3.2.0
