- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/ip.go
- vendor/github.com/packethost/packngo/sshkeys.go
- vendor/vendor.json
- website/docs/r/device.html.markdown
This PR adds the options `public_ipv4_subnet_size` to the packet_device resource. The make it possible to allocate IPv4 subnet on device creation. More on this at
https://help.packet.net/technical/networking/custom-subnet-size
We had a user request for this.  
I had to update the packngo version.
I also wrote an acceptance test for the packet_device module. It takes several minutes, as the device provisioning takes a while.
I am open for comments and suggestions to improve this.
> Add public_ipv4_subnet_size option to packet_device, plus acceptance test

- packet/resource_packet_device.go
This causes user_data to be omitted from log/console output.
Fixes #12
> Set device user_data field to Sensitive

- CHANGELOG.md
- packet/resource_packet_device.go
- website/docs/r/device.html.markdown
This PR adds hw reservation field to the packet_device resource. This makes it possible to utilize customer's reserved hardware in Packet host with Terraform. More info at
https://help.packet.net/technical/deployment-options/reserved-hardware
> Add hardware_reservation_id field to the packet_device resource

- .travis.yml
- README.md
This is necessary before bumping vendored `hashicorp/terraform` to `0.10.3` as it uses some `1.9` features.
> travis: Bump Go to 1.9

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- vendor/github.com/packethost/packngo/ip.go
- vendor/vendor.json
- website/docs/r/device.html.markdown
- access_public_ipv6
- access_public_ipv4
- access_private_ipv4
These are copied from the "network" list of maps for convenience.
Fixes #11
> Add first-level IP address variables

- packet/resource_packet_device.go
- website/docs/r/device.html.markdown
This makes it possible to provision device on reserved hardware without explicitly specifying the UUID of the hw reservation. Packet has customer demand for this.
In Packet this is done by passing `next-available` instead of the hw reservation ID when creating a device. The created device then has the UUID of the used hw reservation in the resource attributes.  
I realize it's a bit terraform-unfriendly, and that's why I had to specify the DiffSuppressFunc. The device creation did not change, but the behavior on update is:
If new hwr\_id (value from tf file) is "next-available" and old hwr\_id (value from API read) is non-empty; then suppress diff (i.e. do skip, even though this "ForceNew" field would normally cause resource update).
It's alright this way I think - if "next-available" is …
> Enable next-available hw resevation in device resource

- packet/resource_packet_reserved_ip_block.go
- packet/resource_packet_reserved_ip_block_test.go
This PR makes it possible to import IP reserved blocks for a project.
It wasn't possible before, because of missing link to parent project in the reserved block resource, but they have put it in place in the API so import is possible.
> make IP reserved block resource importable

- packet/resource_packet_reserved_ip_block.go
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/ip.go
- vendor/vendor.json
There was an API change described in https://github.com/packethost/packngo/pull/47 on 9.10.2017 3:30 UTC
This PR incorporates it to the terraform provider.
Before merging this, I check relevant acceptance tests.
This is a breaking change, so I merge without review. I will ask for re-release.
> reflect API change in IP block reservation

- CHANGELOG.md
- packet/datasource_packet_precreated_ip_block.go
- packet/datasource_packet_precreated_ip_block_test.go
- packet/provider.go
- packet/resource_packet_ip_attachment.go
- packet/resource_packet_reserved_ip_block.go
- website/docs/d/precreated_ip_block.html.markdown
- website/packet.erb
This PR adds a datasource for reserved IP blocks so that users can take advantage of the pre-created IPv6 and IPv4 blocks.
> Add datasource for pre-created (elastic) IP blocks

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
> Fix over-reaching user_data/ipxe_script_url conflict

- README.md
-> changing old, broken links from `hashicorp/terraform-provider-packet` to new, working ones `terraform-providers/terraform-provider-packet`
-> changing `$PROVIDER_NAME` variable to the actual name `packet`.
> readme: fix broken github links and $PROVIDER_NAME

- packet/resource_packet_device.go
After reading the docs a bit I realize that if your provider doesn't support updating
a property the best solution is probably to label said property "ForceNew".
For user_data this is probably a rather desired property, since user_data is often used to
initialize the system. So force recreation of the resource might even be better than updating
user_data, which would still leave users wanting to have their machine reboot or reformatted
(in many instances).
> Set ForceNew for user_data fixing #42

- packet/resource_packet_device.go
- packet/resource_packet_project.go
- packet/resource_packet_ssh_key.go
- packet/resource_packet_volume.go
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/organizations.go
- vendor/github.com/packethost/packngo/payment_methods.go
- vendor/github.com/packethost/packngo/projects.go
- vendor/github.com/packethost/packngo/sshkeys.go
- vendor/github.com/packethost/packngo/volumes.go
- vendor/vendor.json
This incorporates changes from packngo, so that update requests only contain actually changed attributes, and nothing else.
Hopefully, this will fix #56
> bump packngo and fix resource updates

- packet/provider.go
- packet/resource_packet_organization.go
- packet/resource_packet_organization_test.go
- packet/resource_packet_project.go
- packet/resource_packet_project_test.go
- website/docs/r/organization.html.markdown
- website/docs/r/project.html.markdown
- website/packet.erb
Allow create projects with organization id.
```
resource "packet_organization" "test" {
name = "foobar"
description = "test"
website = "http://google.com"
twitter = "miry_sof"
}
resource "packet_project" "foobar" {
name = "foobar"
organization_id = "${packet_organization.test.id}"
}
```
It is example how it could be done.
Another solution to move `packet_organization` under `provider` resource similar to https://www.terraform.io/docs/providers/aws/, with out create and update resources.
> Added Organization resource.

- CHANGELOG.md
- packet/config.go
- packet/datasource_packet_operating_system.go
- packet/datasource_packet_operating_system_test.go
- packet/provider.go
- vendor/github.com/packethost/packngo/README.md
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/email.go
- vendor/github.com/packethost/packngo/events.go
- vendor/github.com/packethost/packngo/hardware_reservations.go
- vendor/github.com/packethost/packngo/ip.go
- vendor/github.com/packethost/packngo/notifications.go
- vendor/github.com/packethost/packngo/operatingsystems.go
- vendor/github.com/packethost/packngo/organizations.go
- vendor/github.com/packethost/packngo/packngo.go
- vendor/github.com/packethost/packngo/projects.go
- vendor/github.com/packethost/packngo/spotmarketrequest.go
- vendor/github.com/packethost/packngo/two_factor_auth.go
- vendor/github.com/packethost/packngo/user.go
- vendor/github.com/packethost/packngo/vpn.go
- vendor/vendor.json
- website/docs/d/operating_system.html.markdown
- website/packet.erb
Here is the new data source for packet provider.
```
make testacc TESTARGS='-run=TestAccPacketOperatingSystem_Basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccPacketOperatingSystem_Basic -timeout 120m
?       github.com/terraform-providers/terraform-provider-packet        [no test files]
=== RUN   TestAccPacketOperatingSystem_Basic
--- PASS: TestAccPacketOperatingSystem_Basic (4.76s)
PASS
ok      github.com/terraform-providers/terraform-provider-packet/packet 4.788s
```
> [datasource] packet_operating_system -> data source

- website/docs/r/device.html.markdown
- website/docs/r/ip_attachment.html.markdown
Updates `help.packet.net` documentation references to use new url structure
> fix broken documentation references

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- website/docs/r/device.html.markdown
This PR sorts the network connections in device's `network` list to specific order - first is private IPv4, second is public IPv4 and third is IPv6. This will allow to access attributes of a particular interface configuration, which is necessary in BGP setup in #88.
> keep device networks in specific order

- packet/provider.go
- packet/resource_packet_bgp_session.go
- packet/resource_packet_bgp_session_test.go
- packet/resource_packet_project.go
- packet/resource_packet_project_test.go
- website/docs/r/bgp_session.html.markdown
- website/docs/r/project.html.markdown
This PR will add support for BGP networking API resources as decribed in https://help.packet.net/article/56-bgp
Ready for review.
The usage is illustrated in the bgp_session resource doc.
> BGP support: extend project by BGP Config, new resource for BGP session

- CHANGELOG.md
- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- website/docs/r/bgp_session.html.markdown
- website/docs/r/device.html.markdown
I have changed the order of the elements in the network List attribute in #89. It was not a great idea considering how many users depend on the implicit order of the network configuration:
https://github.com/search?p=2&q=%22network.0.address%22+ssh+packet+terraform&type=Code
This PR reverts the order of the items in the network, so that it's like before, i.e.
0. Public IPv4
1. IPv6
2. Private IPv4
plus documentation.
> Hotfix of network attribute order for packet_device

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- website/docs/r/device.html.markdown
This PR makes it possible to take advantage of Packet API dynamic facility selection. When creating new device, user can specify list of facility codes in `facilities` attribute. Device is then deployed to first facility with free capacity.
Fixes #90
> allow list of facilities for packet_device

- packet/datasource_packet_precreated_ip_block_test.go
- packet/resource_packet_bgp_session_test.go
- packet/resource_packet_device_test.go
- packet/resource_packet_ip_attachment_test.go
- packet/resource_packet_spot_market_request_test.go
- packet/resource_packet_volume_attachment_test.go
- website/docs/d/operating_system.html.markdown
- website/docs/d/precreated_ip_block.html.markdown
- website/docs/d/spot_market_price.html.markdown
- website/docs/index.html.markdown
- website/docs/r/bgp_session.html.markdown
- website/docs/r/device.html.markdown
- website/docs/r/spot_market_request.html.markdown
- website/docs/r/ssh_key.html.markdown
- website/docs/r/volume_attachment.html.markdown
I think that giving real example will more, AFAIK `plan = "baremetal_1"` is not something that would work.
> [doc] Use real plans in the doc

- packet/errors.go
- packet/resource_packet_reserved_ip_block.go
in specific, when an invalid token is used, a 401 will be generated without an error message
this now passes back up the 401 and an error string to the user rather than a blank message
previously, the user would be presented with no error string and would have to turn on TF_LOG=DEBUG
to figure out what happened
> create useful error string when none generated from packngo

- packet/provider.go
- packet/resource_packet_device.go
- packet/resource_packet_project_ssh_key.go
- packet/resource_packet_project_ssh_key_test.go
- packet/resource_packet_ssh_key.go
- website/docs/r/device.html.markdown
- website/docs/r/project_ssh_key.html.markdown
- website/packet.erb
This PR adds a resource for project SSH keys, keys which are (not user-, but) project-specific.
If project SSH keys are passed to a new device, no user keys are injected.
> Project ssh keys

- CHANGELOG.md
- packet/resource_packet_bgp_session.go
- packet/resource_packet_ip_attachment.go
- packet/resource_packet_project_ssh_key.go
- packet/resource_packet_reserved_ip_block.go
- packet/resource_packet_spot_market_request.go
- packet/resource_packet_vlan.go
- packet/resource_packet_volume_attachment.go
aligning error handling to be the same as the rest of the code base
properly handle when a resource has been removed outside of Terraform
resolves https://github.com/terraform-providers/terraform-provider-packet/issues/108
> Handle resources that have been removed outside of TF

- website/docs/r/project.html.markdown
In Markdown unordered lists need an empty line before their start.
> Fix unordered lists

- website/docs/r/device.html.markdown
- website/docs/r/ip_attachment.html.markdown
- website/docs/r/project.html.markdown
- website/docs/r/spot_market_request.html.markdown
- website/docs/r/vlan.html.markdown
This is a docs fix, so that resouce docs point to proper articles in support.packet.com
> Fix doc links to aim to support.packet.com

- website/packet.erb
> docs/provider: Sort resource list and include packet_ prefix for data sources in sidebar

- packet/resource_packet_bgp_session.go
- packet/resource_packet_bgp_session_test.go
- website/docs/r/bgp_session.html.markdown
This PR adds a bool flag to packet_bgp_session to set the default route policy.
@patrickdevivo Please review. Is False by default OK?
> add default_route flag to bgp session

- packet/resource_packet_port_vlan_attachment.go
- packet/resource_packet_port_vlan_attachment_test.go
This PR fixes the usecase for l2-bonded where vlans are added to bonded port (bond0).
Initially I assumed that a port must be removed from bond before VLAN is added to it, but it's not the case for l2-bonded, so I fix it with this PR.
> fix packet_port_vlan_attachment resource for layer2-bonded usecase

- packet/resource_packet_device.go
- website/docs/r/device.html.markdown
This PR makes the packet_device resource disregard the network type of the deivce unless the user specifies it. It will make provisioning faster, and make the packet_device independent of L2 bugs such as https://github.com/packethost/packngo/issues/141
fixes #138
> disregard network_type of packet_device unless the user specifies it

- packet/datasource_packet_precreated_ip_block_test.go
- packet/resource_packet_bgp_session_test.go
- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- packet/resource_packet_ip_attachment_test.go
- packet/resource_packet_port_vlan_attachment_test.go
- packet/resource_packet_project_ssh_key_test.go
- website/docs/d/operating_system.html.markdown
- website/docs/d/precreated_ip_block.html.markdown
- website/docs/r/bgp_session.html.markdown
- website/docs/r/device.html.markdown
- website/docs/r/port_vlan_attachment.html.markdown
- website/docs/r/project_ssh_key.html.markdown
- website/docs/r/ssh_key.html.markdown
- website/docs/r/volume_attachment.html.markdown
This PR removes `facility` attr in favor of more general `facilities` (taking advantage of dynamically specified deployment location). 
It also adds a Computed attr `deployed_facility` to the packet_device resource
Fixes #141
> Remove deprecated 'facility' attr, fix device import

- packet/resource_packet_device.go
- website/docs/r/device.html.markdown
This PR adds functionality allowing users to select which IP address type a new device should have.
It's mainly to enable provisioning devices without public IP addresses.
> Add field for selecting IP Address types when creating device

- packet/provider.go
- packet/resource_packet_port_vlan_attachment.go
- packet/resource_packet_port_vlan_attachment_test.go
- vendor/github.com/hashicorp/terraform/helper/mutexkv/mutexkv.go
- vendor/modules.txt
Packet's API reports HTTP 500 Internal Server Error when 2+ requests are issued for assigning a VLAN to a port in parallel, as demonstrated by attached test suite.
I have already contacted Packet support and they said the API doesn't support parallel assignment at this point and they agreed the API should respond 4xx instead of 5xx in such cases. They plan to fix the API in that sense, but implementation/allowing parallel execution may take more time.
I'm therefore adding mutex to avoid parallel VLAN assignments until this is actually fixed/implemented.
```
$ make testacc TEST=./packet TESTARGS='-run=TestAccPacketPortVlanAttachment_HybridMultipleVlans'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./packet -v …
```
> resource/packet_port_vlan_attachment: Avoid parallel assignment

- packet/datasource_packet_precreated_ip_block_test.go
- packet/resource_packet_bgp_session_test.go
- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- packet/resource_packet_ip_attachment_test.go
- packet/resource_packet_port_vlan_attachment_test.go
- packet/resource_packet_project.go
- packet/resource_packet_project_ssh_key_test.go
- packet/resource_packet_project_test.go
- packet/resource_packet_reserved_ip_block_test.go
- packet/resource_packet_spot_market_request_test.go
- packet/resource_packet_vlan_test.go
- packet/resource_packet_volume_attachment_test.go
- packet/resource_packet_volume_test.go
Updating project naming to make cleanup easier, and leaky tests more apparent.
> Clean up acceptance test naming

- packet/datasource_packet_operating_system.go
- packet/datasource_packet_operating_system_test.go
This PR reworks the OS datasource filtering and add tests for the case reported in #155.
Fixes #155
> Rework operating systems datasource filtering and add tests

- packet/resource_packet_device.go
- website/docs/r/device.html.markdown
This PR adds an attribute to the packet_device resource - `wait_for_reservation_deprovision` which, when set, causes Terraform wait until hw reservation, where the removed device was deployed, is again provisionable. Fixes #124
> Reservation deprovision guard on device removal

- packet/resource_packet_reserved_ip_block.go
- packet/resource_packet_reserved_ip_block_test.go
- website/docs/r/reserved_ip_block.html.markdown
This adds `description` attr to `packet_reserved_ip_block`, and fixes #163
> Add description attr to packet_reserved_ip_block, tests and doc

- website/docs/r/project_ssh_key.html.markdown
I believe at some point the documented behavior matched was we were doing at packet, but that was deemed that we were doing it wrong so was changed. Both the portal and kb pages document an additive behavior.
> Remove incorrect statemets wrt project ssh keys

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
This PR makes the user_data field of packet_device not ForceNew. The change is Packet internal request.
> Make user_data not ForceNew, add update test

- packet/datasource_packet_ip_block_ranges.go
- packet/datasource_packet_ip_block_ranges_test.go
- packet/provider.go
- website/docs/d/ip_block_ranges.html.markdown
- website/packet.erb
The PR adds a datasource for listing CIDR expressions for IP block allocated for a project. I had a request from Packet to do this.
> Add ip_block_ranges datasource, doc

- packet/datasource_packet_device.go
- packet/datasource_packet_device_test.go
- packet/datasource_packet_spot_market_request.go
- packet/datasource_packet_spot_market_request_test.go
- packet/provider.go
- website/docs/d/device.html.markdown
- website/docs/d/spot_market_request.html.markdown
- website/packet.erb
This PR adds a datasource for spot market request, so that users can check the device IDs of spawned devices.
fixes #107.
> Datasource for spot market request

- packet/resource_packet_ssh_key.go
- packet/resource_packet_ssh_key_test.go
This PR enables packet_ssh_key resource import and adds the acceptance test for it.
> Enable packet_ssh_key resource import

- packet/resource_packet_organization.go
- packet/resource_packet_organization_test.go
Enables packet_organization resource import and adds the acceptance test for it. Related to #51 
Organization import worked when I tested it manually. The import test failed on my local environment since I have no permission to create a new organization.
```
=== RUN   TestAccOrg_importBasic
2019/10/28 22:35:30 [DEBUG] POST https://api.packet.net/organizations
--- FAIL: TestAccOrg_importBasic (3.01s)
testing.go:569: Step 0 error: errors during apply:
Error: Sorry! You have reached the maximum number of organizations you can create (1). The Packet team has been notified of this and will be in touch shortly. If this is urgent, please email help@packet.net to request additional deployment capacity.
```
> Enable packet_organization resource import & acc test

- packet/datasource_packet_organization_test.go
- packet/resource_packet_organization_test.go
This is to fix Acceptance test for organization datasource. The Teamcity runs were failing with
```
------- Stdout: -------
=== RUN   TestAccOrgDataSource_Basic
--- FAIL: TestAccOrgDataSource_Basic (5.70s)
testing.go:569: Step 0 error: errors during apply:
Error: too many organizations found with name foobar (found 2, expected 1)
on /opt/teamcity-agent/temp/buildTmp/tf-test103161711/main.tf line 11:
(source code not available)
testing.go:630: Error destroying resource! WARNING: Dangling resources
may exist. The full state and error is shown below.
Error: errors during refresh: too many organizations found with name foobar (found 2, expected 1)
State: <nil>
```
..this should fix the test fail
> change org name in org datasource test

- packet/resource_packet_project_ssh_key.go
- packet/resource_packet_ssh_key.go
- packet/resource_packet_ssh_key_test.go
- website/docs/r/project_ssh_key.html.markdown
- website/docs/r/ssh_key.html.markdown
This PR simplifies handling of the SSH key resources. It also implements import of project_ssh_key resources. 
#51, update ssh_keys checkbox when this is merged.
> Add import of project SSH keys

- packet/config.go
This is a hotfix for request retries on HTTP 5xx. 
In Packet API, HTTP 5xx responses usually indicate an issue which is not recoverable in immediate retries (even with exponential backoff).
@mmlb Manny, could you please clarify previous statement? Or could you make someone API-side-aware to explain here which HTTP errors are recoverable, if any?
> HTTP client hotfix: don't retry on HTTP 5xx

- packet/resource_packet_port_vlan_attachment.go
In Packet API, only one VLAN can be detached at a time. This PR adds a mutex guard around the detachment API call.
> Add mutex guard to VLAN detachment

- packet/resource_packet_port_vlan_attachment_test.go
The Acceptance tests for VLAN attachment notoriously fail (#182). 
They fail either because facility `dfw2` is out of capacity of L2-capacble device plans, or there are timeouts.
This PR will switch the facility to "nrt1", hopefully making the tests succeed for some time. This is obviously just a temporary solution, but it's good to see the VLAN tests succeed again, after quite some changes in the provider.
Permanent solution would be to get the capacity via a datasource and run the test devices where the capacity is not "unavailable".
closes #182 temporarily
> fix acceptance tests for Layer 2 networking (ports and VLANS)

- CHANGELOG.md
- packet/resource_packet_connect.go
- website/docs/r/connect.html.markdown
- website/packet.erb
Removing packet_connect, major release, according to https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-data-source-or-resource-removal
> removed packet_conect

- packet/resource_packet_bgp_session.go
- packet/resource_packet_bgp_session_test.go
This patch would create the BGP session using the provided address
family.
The tests provided in this patch would not actually catch the error,
since they since they jsut test for valid configuraiton, not the objects
used when the session is created.
By the way, I have not tested this patch in any way.
Maybe fixes https://github.com/terraform-providers/terraform-provider-packet/issues/206
> Use the address family provided, rather than just ipv4

- packet/errors.go
This is a result of discussion with @smintz 
When terraform provider gets 404 NotFound on a resource which is listed in the tf state (was created or imported by/to terraform), the standard way to handle this is to remove the resource from the state and consider it gone. Subsequent `apply` will attempt to create the resource again.
@smintz mentioned that he was running to problems when HTTP 404 was returned by the load balancer (instead of the API). The resource still exists, but terraform then forgets about it, and attempts to re-create. This is obviously not good, it would be better to raise the 404 Error from the load balancer.
The goal of this PR is to distinguish HTTP 404 from API and from load balancer. If it's 404 from the API, the resource is marked as gone, but if it's not, the …
> check if HTTP 404 Not Found comes indeed from API

- packet/datasource_packet_device_test.go
- packet/datasource_packet_ip_block_ranges_test.go
- packet/datasource_packet_organization_test.go
- packet/datasource_packet_precreated_ip_block_test.go
- packet/datasource_packet_spot_market_request_test.go
- packet/datasource_packet_volume_test.go
- packet/resource_packet_bgp_session_test.go
- packet/resource_packet_device_test.go
- packet/resource_packet_ip_attachment_test.go
- packet/resource_packet_organization_test.go
- packet/resource_packet_port_vlan_attachment_test.go
- packet/resource_packet_project_ssh_key_test.go
- packet/resource_packet_project_test.go
- packet/resource_packet_spot_market_request.go
- packet/resource_packet_spot_market_request_test.go
- packet/resource_packet_ssh_key_test.go
- packet/resource_packet_volume_attachment_test.go
- packet/sweeper_test.go
We had congestion of the Terraform test account. This PR adds sweepers to clean resoruces from failed tests.
> Add sweepers to clean residual resources from Acceptance tests

- packet/resource_packet_device.go
- packet/resource_packet_device_test.go
- packet/resource_packet_spot_market_request_test.go
- packet/resource_packet_volume_test.go
pre-sweeper run in acceptance tests is failing because of residual volumes
This PR adds sweeper for volumes.
> Compound Hotix: volume sweeper, TF state fix, spot market test fix

- packet/datasource_packet_organization_test.go
- packet/resource_packet_organization_test.go
I noticed that there were remnant organizations in the Acceptance test account. This PR adds code to properly sweep them.
It also improved naming of test organizations, to avoid name clash between datasource and resource test for org.
> Add sweepers for Organizations

- CHANGELOG.md
- packet/resource_packet_device.go
- packet/resource_packet_port_vlan_attachment_test.go
- website/docs/r/device.html.markdown
- website/docs/r/port_vlan_attachment.html.markdown
Due process for removal of ip_address_type and the subnet size attrs.
Both are replaced with ip_address attribute.
> device attr ip_address_type from deprecated to removed

- packet/helpers_device.go
As [reported in Slack](https://packetcommunity.slack.com/archives/CU7HC3RJP/p1594207906242100), `nil` responses were being converted to `string`, causing the following
error pattern:
```
[DEBUG] GET https://api.packet.net/devices/{uuid}?include=project,facility
[TRACE] Waiting 10s before next try
[WARN] WaitForState timeout after 1h0m0s
[WARN] WaitForState starting 30s refresh grace period
panic: interface conversion:
interface {} is nil, not string
```
---
*The terraform-plugin-sdk code triggering this seems related ([based on EC2 comments](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/helper/resource/state.go#L16)) to the AWS provider, which has [evolved the pattern](https://github.com/terraform-providers/terraform-provider-aws/blob/711107a93685d175c3a00dbee50ac5ee26d8c08 …
> fix conversion from nil during WaitForState loops

- packet/provider.go
- packet/resource_packet_device.go
- packet/resource_packet_device_network_type.go
- packet/resource_packet_device_test.go
- packet/resource_packet_port_vlan_attachment_test.go
- website/docs/r/device.html.markdown
- website/docs/r/device_network_type.markdown
- website/docs/r/port_vlan_attachment.html.markdown
- website/packet.erb
This PR decouples the Network Mode handling from the device resource. We've had a lot of issues with the network mode reading, setting and waiting for it. If the API calls fails, it's better if it's in a separate resource, because some devices have very long provisioning times and re-creating of fixing TF state becomes really ugly.
Relevant issues:
* The network mode handling created a lot issues in Packet Anthos: https://github.com/packet-labs/google-anthos/issues/25#issuecomment-656471472
* https://github.com/terraform-providers/terraform-provider-packet/issues/238 Good old network state API cache issue - network state of a device is changed, but the /device/\<uuid\> endpoint is cached and doesn't update, so TF hangs. Third time it's resurrected.
* same as above but reported in packngo, …
> Add new resource for Device Network Mode

- CHANGELOG.md
Per the [versioning best practices](https://www.terraform.io/docs/extend/best-practices/versioning.html#categorization),
BREAKING CHANGES should be called out in the changelog.
This was missed in v3.0.0 for the read-only change to `packet_device.network_type`, this PR adds a note about this.
> update 3.0.0 CHANGELOG for BREAKING CHANGES

- .github/workflows/acctest.yml
- .gitignore
This adds acceptance testing back into the PR workflow using Github Actions.
Previously, this was performed on Hashicorp managed servers in TeamCity.
I would like to restrict the PR builds to ones that have received a label of preliminary acceptance (something like "ok-to-test"), but I'd be ok with full acceptance testing being introduced before then (if we disable build-on-PR and only use build-on-push to the default branch).
I'm not sure if we want to add these environment variables to the build at this time, we can always add them later:
```
TF_SCHEMA_PANIC_ON_ERROR: "1" # I think this will be the default in TF sdk2
TF_LOG: "DEBUG"
```
> add GH workflow for acceptance testing

- .github/workflows/acctest.yml
Pull requests which are based on `origin/` branches will be `acctest`'ed
because of the [`push` rule](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#push). The [`pull_request` rule](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request) can not work because
GH actions does not pass secrets to pull requests from forks.
Signed-off-by: Marques Johansson <marques@packet.com>
> tests: don't attempt acctest on pull requests

- go.mod
- go.sum
- packet/datasource_packet_precreated_ip_block.go
- packet/errors.go
- packet/resource_packet_reserved_ip_block.go
This is for consideration of #264.
This may make `d.Set` blocks easier to read, if implemented everywhere, and it would ensure that `d.Set` errors are being checked and reported.  Without a function like `setMap` we could end up with hundreds of `if err := d.Set(...); err != nil { return err }` blocks added to address #264.
One potential down-side of this, is that Terraform plugins for VS Code (and perhaps linters?) that are smart about `d.Set`, may not be able to provide guidance using this approach.  I don't know if that is an actual capability of linters and IDE-plugins.
`github.com/hashicorp/go-multierror` is used to collect and collate the `d.Set` errors.
> adds setMap to check errors when setting IP block data

- CHANGELOG.md
- go.mod
- go.sum
Updates the Packngo version to one that is aware of the new Equinix Metal API endpoint at (api.equinix.com/metal/v1).
Users will want to revise any network filters to permit the new endpoint.
Nothing else changes about packngo in this version change (including PACKNGO_DEBUG and the default auth token environment variables).
> update packngo to 0.4.1 (new API endpoint api.equinix.com/metal/v1)

- GNUmakefile
This PR cleans GNUmakefile, it removes targets for old doc format preview and lint tools, and adds targets for bflad/tfproviderlint and bflad/tfproviderdocs. Except for misspel, all the lint tools are run from Docker, so they can be easily plugged in to the CI via Github actions.
#258  #275  are related issues
> Makefile: lint targets upkeep

- CHANGELOG.md
- go.mod
- go.sum
- packet/datasource_packet_device.go
- packet/helpers_device.go
- packet/resource_packet_device.go
- packet/resource_packet_device_network_type.go
- vendor/github.com/packethost/packngo/Makefile
- vendor/github.com/packethost/packngo/OWNERS.md
- vendor/github.com/packethost/packngo/devices.go
- vendor/github.com/packethost/packngo/packngo.go
- vendor/github.com/packethost/packngo/ports.go
- vendor/modules.txt
By updating to packngo v0.5.0, the provider will make use of the new
api.equinix.com/metal/v1 URLs (rather than api.packet.net).
The network type detection should be improved, as a result, the network
type conversion should be improved.
Devices listing can now use the `search` parameter, which should improve
the performance of hostname lookups in the `packet_device` data source.
Signed-off-by: Marques Johansson <mjohansson@equinix.com>
> packngo v0.5.0

- .github/workflows/acctest.yml
Signed-off-by: Tomas Karasek <tom.to.the.k@gmail.com>
Fixes #285 
Let's see if the Acctest runs are free of the set-env warning.
> Update versions of github actions containers to address CVE-2020-15228

- go.sum
- packet/resource_packet_spot_market_request.go
Implemented on behalf of @grahamc; mostly implemented through guesswork based on grepping through `resource_packet_device.go`. I probably missed something, ~~and this is completely untested~~.
Requires on https://github.com/packethost/packngo/pull/218.
cc @grahamc 
EDIT: Also impl `tags`. Again, probably missed something, ~~completely untested,~~ etc., etc.
> resource_packet_spot_market_request: impl missing parameters

- .github/workflows/acctest.yml
The daily cron is not needed for a few reasons:
* PRs are incoming daily
* The cron schedule regularly bumps into PR builds
* The sweepers stomp over active tests
* The packet provider and equinix-metal provider are on the same
schedule.
Signed-off-by: Marques Johansson <mjohansson@equinix.com>
> remove daily cron acceptance tests

- CHANGELOG.md
- packet/resource_packet_device.go
> fix BC break with hardware_reservation_id = next-available handling
